language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: radiant-spire-31689
  api_key: ${HEROKU_API_KEY}
